language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

# CI support for bors mergebot
branches:
  only:
    - staging
    - trying
    - master
