language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test

# CI support for bors mergebot
branches:
  only:
    - staging
    - trying
    - master
